### ISSUE TITLE
Clarification request for adding annotation to 'Source only'

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#100]
In session view, I select Source only's add annotation option. When I get to the working window, I am offered to add the annotation re the translation or the respeaking. I am confused because I thought I was going to leave an annotation about the source only.  Am I missing something ?

In addition, I clicked the session name to back out of where I was. When I tried to repeat my steps, the previous attempt showed up although I have not saved it.

![image](https://cloud.githubusercontent.com/assets/18228507/14941894/fd33f11e-0fef-11e6-8110-3287f5404614.png)

I was able to delete the two attempts at the session level.

Just would like request more info/help re what 'Source only annotation' is intended to be.

**Comment by Lingomat** [comment]
Basically this is the same as it was at first. You have translation and respeaking audio available. But if you add an annotation for 'source only' they are not joined to the translation/respeaking audio, they are stand alone. 

So in this view, if you worked on 3 and 4, you would only hear the source. If you worked on 1, you would hear the source and the translation.

You can still manually join the translation and respeaking (and split) by clicking on the coloured boxes to the right of the microphone. However the new scheme is supposed to be a clearer way to do this. When you select source only, we assume you just want to listen to the source audio. It doesn't mean you can't work on other things in the annotation UI if you want.

**Comment by Netesten** [comment]
Thanks! I had trouble understanding this before - all becomes clear when I look at the Help - sorry!
