### ISSUE TITLE
Improve debug view (incorporating filesystem view)

### ISSUE THREAD

**Issue by Lingomat** [aikuma/aikuma-ng#112]
You can type filesystem:persistent/ and get a list of the files on a browser, but I don't know if one can do that in a Chrome app.

The goal here is allowing someone to access a file from persistent storage. It doesn't have to be pretty, it's more of a feature in case something goes badly wrong. It's hard to find out where the files are on the FS.

**Comment by Lingomat** [comment]
Debug is currently in settings. There are strings displayed even if debug is off. Let's fix up the debug view properly:

1. No debug information is in settings. Settings is for settings.
2. When debug mode is switched on, a debug menu item appears on the navbar
3. All debug material moves into this new nav view. Including the buttons to wipe/reset DB etc.
4. Adopt the current icon for 'report issue' and select a new icon for report issue.

**Comment by lisaslyis** [comment]
The commit #35743a is related to this issue.

1. Settings have only setting-related switches.
2. All debug materials(3 debug buttons and filesystem/DB view) are moved to debug page.
3. New debug menu is created and linked to the debug page. This menu is only shown when user is logged in and turned on the debug option in the settings page.
4. Current 'report issue' icon is used for new debug menu. and an exclamation inside triangle is used as an icon for the 'report issue' menu

**Comment by Lingomat** [comment]
Excellent!
