### ISSUE TITLE
Set up secure https hosting 

### ISSUE THREAD

**Issue by Lingomat** [aikuma/aikuma-ng#14]
Necessary for serving development builds on the web (microphone input wont work unless it's https).

This can be an external host, so long as we have common ftp access or whatever.

Steven, perhaps there is already somewhere suitable? We only need a sub folder or whatever... or can it be served from Github, I'm not clear.

**Comment by stevenbird** [comment]
NB https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

**Comment by stevenbird** [comment]
Ongoing work to set this up as a submodule

**Comment by Lingomat** [comment]
What is the status of this? Specifically, what must be done to update the gh-pages branch?

**Comment by Lingomat** [comment]
I think this is now redundant given how easy it is to install the Chrome app.
