### ISSUE TITLE
Build Chrome Packaged App and deploy to Chrome Web Store

### ISSUE THREAD

**Issue by Lingomat** [aikuma/aikuma-ng#15]
This may result in further issues. We also need to review the update process.

**Comment by Lingomat** [comment]
Minimal features for the first deploy of the Aikuma-NG beta:

1. Ability to transcribe.
2. Ability to export SRTs
3. Some support for respeaking/translation or temporarily disabling respeaking/translation
4. Minimal about/help information, particularly relating to status of the beta.

**Comment by stevenbird** [comment]
I think support for respeaking and interpreting is axiomatic for software called Aikuma!

**Comment by Lingomat** [comment]
Nod. Shooting straight for that.

**Comment by Lingomat** [comment]
Done.
