### ISSUE TITLE
App window: being able to re-size

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#25]
App window appears to be either maximised or relatively small. If a user could choose the window size, could have other apps or windows on-screen for reference

**Comment by Lingomat** [comment]
Hmm, I thought it could be, you can't drag the edges?

Still, it seems if we define a reasonable window size as well as requesting maximized, perhaps when the user minimizes, they will get the second window size. I will update the manifest and try it. This might be a reasonable solution for #43 as well.

**Comment by Lingomat** [comment]
@Netesten I have changed this so the small window alternative (to full screen) should be of reasonable size. Please tell me if this worked.

**Comment by Netesten** [comment]
​Yep, thanks. I am able to adjust size pulling on corner or
vertical/horizontal edges!

[image: Inline images 2]
