### ISSUE TITLE
Left menu bar

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma-ng#27]
Left menu bar can only be seen when the app is fullscreen. I can see a few options:

* app opens in fullscreen by default
* there's some sort of hint to users to make it go fullscreen
* there's a hamburger menu in the top left (but this seems dated now)
* using a tab bar at the bottom of the screen, which can disappear, cf http://techcrunch.com/2014/05/24/before-the-hamburger-button-kills-you/

**Comment by Lingomat** [comment]
The Chrome App launches full screen though? It does here.

**Comment by Lingomat** [comment]
I think bottom tab bar is perfect for mobile but I don't recall seeing anyone use it for desktop?

**Comment by hatton** [comment]
Is it intentional to not show it if now full screen, or only if you run out of space? There's plenty of room for it. @stevenbird we recently solved this same issue via a hamburger menu that slides out persistent drawer (hamburger becomes an "x" when open, if you want to close it back up). And now you inform me that idiom it is out of date. Sigh :-)

**Comment by Lingomat** [comment]
The idea is that it's hidden only when the window/screen is narrower than a particular point.

It's probably a bit overzealous. Frankly we need a substantial pass over the responsiveness of the design. I'd really like to do that in conjunction with testing on a particular device for a particular usage case, like on a tablet. A project for later in the year...

... and the move to mobile will, I think, involve disabling some aspects and completely re implementing the templates with use of bottom sheets with a bottom tab bar.

On the hamburger, I agree on desktops. On mobiles, pull out menus cover a substantial part of the screen, and then snap it back in place. In this case it's more like a mode switch, or a dialog.
