### ISSUE TITLE
Sign up activity

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma-ng#29]
The add-person button should take us to a sign up activity, to elicit name and email, rather than having them default to `anonymous` and `foo@gmail.com` and need to be edited.

(This is independent of whether we want to verify the email, or authenticate the user.)

**Comment by stevenbird** [comment]
NB this is for the account owner, not to identify a speaker who is being recorded. So we can assume they have an email address.

**Comment by Lingomat** [comment]
This seems reasonable. We just trigger the add user and then immediately bring up the profile editor.

**Comment by Lingomat** [comment]
Good work but it needs a tweak.

Remove validation string (remember I have to translate all this stuff) and use a visual feedback to indicate a valid email address. Angular Material provides a means to do this, and there's a good example in the demos section of their site.

**Comment by Lingomat** [comment]
This can be the prototype of input validation more widely. For example, language selectors and session title, where these fields are mandatory before a new recording can be saved, they have some style like a red outline or underline.

**Comment by Lingomat** [comment]
We've adopted a validation scheme that is more along the lines of tips rather than errors. People should see anything that looks like an error just because they haven't typed something yet. Although it should explain why they can't do something like confirm/save.
