### ISSUE TITLE
Text hints

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma-ng#32]
I think the text entry fields can be shorter, e.g.:
* Enter date -> Date
* Add titles -> Title (usually there'll just be one, the hint can stay there
* Add languages -> Language
* Add more -> More (?)
* Add people -> Speaker
* Add tags -> Tags

I think the icons don't need text hints at all – just use icons?
* review (just the play triangle)
* play (just the play triangle)
* clear (just the trash icon)
* save (just the diskette icon
* record (just the record icon)
* record respeaking (just the refresh icon)
* record translation (just the translate icon)

**Comment by Lingomat** [comment]
Hmm, yes. Although in Chinese I think it's better to retain the add. So I'll just make this change in the localisation rather than removing the strings. I'll comment out the text in the buttons, let's see how it looks.
