### ISSUE TITLE
Annotation button

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma-ng#33]
How about replacing this with a transcription button (e.g. `text-align-left`). Then circle-plus is only for new session.

**Comment by Lingomat** [comment]
I don't follow, what transcription button? 

I don't think it's bad to reuse an element which means 'add' so long as it's not confusing (like the person add /session add was).

**Comment by Lingomat** [comment]
I think you meant use a different + annotation button on the session view. This was introduced around 905 or so. Suggestions for a better material design icon to represent annotations are welcome...
