### ISSUE TITLE
Listen to a respeaking

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma-ng#34]
Add functionality that allows users to listen to respeakings and translations

**Comment by Lingomat** [comment]
On the status screen? Can you suggest how it might look. We could play them interleaved with source.

**Comment by stevenbird** [comment]
Is there any place to play a respeaking?

Ultimately, it should be possible to play back respeakings and translations in a variety of ways, on their own or interleaved with each other. For now though, it's enough to be able to hear a respeaking or translation interleaved with the source.

**Comment by Lingomat** [comment]
We still need an UI for this. I'm thinking that there should be playback options next to the actual respeaking and translation record/edit menus. Perhaps a speaker icon just like the annotation UI which triggers a menu offering up the same respeaking channels but triggering playback instead.

**Comment by Lingomat** [comment]
First pass at this is in the master branch. I did the best I could at a UI. I couldn't come up with a decent looking system based on a separate playback popup menu. So we lack the ability to select if you want to interleave the audio or not. 

I think I'm inclined not to care. If the user really just wants to review respeaking/translation only, they can go to the annotation UI to do that.
