### ISSUE TITLE
Improve Chrome Web store description and About page text

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#39]
Spotted a few that could be amended:
maintainance -> maintenance
acccomplish -> accomplish
instuctions -> instructions
respeaking/transation -> respeaking/translation 
annotatons -> annotations

**Comment by Netesten** [comment]
Just spotted another small one: 'Aikuma-NG is the result if an international research project ': 'if' to become 'of'

**Comment by stevenbird** [comment]
@Lingomat feel free to assign this one to me

**Comment by Lingomat** [comment]
Thank you, I had fixed some of these typos but the text is still in need of improvement.

**Comment by Lingomat** [comment]
Note that the Chrome Web Store description is set when we upload the app. So I placed the text into description in the root of the repo.

**Comment by Netesten** [comment]
you are welcome!xxx

**Comment by Netesten** [comment]
Just spotted: Were working on better documentation...: I think that 'Were' to become 'We're' (contraction of 'we are').

**Comment by Netesten** [comment]
The updated text with six points is an improvement and reads well, I think.
