### ISSUE TITLE
Annotate and Translate on-screen help for the clueless?

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#40]
[annotate screenshot1.docx](https://github.com/aikuma/aikuma-ng/files/201239/annotate.screenshot1.docx)

When I am in a session (where I have recorded speech, respoken and translated) and I select '+' to add an annotation, in the popupwindow I can select a language and the type of annotation, but after that I cannot see what I need to do to annotate.

**Comment by Netesten** [comment]
My inexperience is hindering me. I have now managed to muddle my way into annotating. Will try to replicate! 
A remaining request might be: clearer on-screen help for new users of the app maybe?

**Comment by Netesten** [comment]
In addition, please could there be on-screen help for the Translate feature as I am struggling to review what I recorded. Thanks. Please dismiss if not appropriate.

**Comment by Lingomat** [comment]
It's highly appropriate. I wonder if you could describe how you might like to view help? Consider that we can display animated pictures which show how to do something, but there might be a good number of them. Do we put it in one large online help dialog (there is a rudimentary one with the question mark under the waveform)?

I'm minded to have the pop-up help as a key reference.

Then implement an actual video tutorial which could be accessed from that pop up and other plays like the getting started page accessed from the nav bar. Does that sound reasonable?

**Comment by Netesten** [comment]
appreciate your reply.

may i respond tomorrow night? let me know if that is too late

**Comment by Lingomat** [comment]
Annotate has improved help. Click on the question mark/help icon underneath the waveform. Feedback welcome.

**Comment by Netesten** [comment]
Thanks, I have been able to leave a Comment and Annotation. 
Do you think that a similar Help Text could be made available for Translate?
I appear to be struggling with listening to one translation.

**Comment by Netesten** [comment]
Was thinking, when Aikuma is fullscreen, is possible to have the Help text pop up under the active task window, and leave the active task window so that the user can read the Help and have a go? (as opposed to Help text blocks active windows and active window becomes inactive?

**Comment by Netesten** [comment]
[aikuma annotate help window.docx](https://github.com/aikuma/aikuma-ng/files/202536/aikuma.annotate.help.window.docx)

**Comment by Netesten** [comment]
Can't quite see how to delete a translation. I seem to have made two by accident.

**Comment by Netesten** [comment]
Just a note re speaker button
![image](https://cloud.githubusercontent.com/assets/18228507/14250767/36ff534e-fac3-11e5-9b3b-754965fa130c.png)

Can't see how to select Translation- can only see Source and Respeaking. Mentioning In case it helps.

**Comment by Netesten** [comment]
Further to 
"Consider that we can display animated pictures which show how to do something, but there might be a good number of them. Do we put it in one large online help dialog (there is a rudimentary one with the question mark under the waveform)?

I'm minded to have the pop-up help as a key reference.

Then implement an actual video tutorial which could be accessed from that pop up and other plays like the getting started page accessed from the nav bar. Does that sound reasonable?"

I think that animated pics, online help (is that the same as onscreen help or in addition to?), video tutorial. I have not had the luxury of time to mull this over, but one thought is: bite-size tutorials 
- have a box for: New, I need help with everything or Pro, only show help lite (along those lines).
- Home page: you have 'add new session' which is great. what about 'delete a session/manage sessions' or upload to database/share ?
- Record new and all other pages: would be nice to have a help text like Annotate and was thinking of help prompts focused on purpose of the page

Another thought: can the contents of this database be imported into any ISO (or whatever standards exist for the field) linguistics databases ?

**Comment by Lingomat** [comment]
I haven't forgotten about this, I've just been busy with urgent fixes. However I'll point out, you can only use the audio of respeaking or translation in that given track, so if you have both, you need two tracks. I'm not sure how to make this more clear. It's a limitation we'd like to remove at some point but it requires a new approach to the annotation UI.

**Comment by Netesten** [comment]
Thanks, Mat. I don't think I understand what you are saying. Maybe other
testers will be better at this.
I am understanding it as for each recording in a treasure language, that
the user can either respeak OR translate, but not both?
Not sure what is meant by two 'tracks'.

Sorry!
