### ISSUE TITLE
Session date field amendment not being saved

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#41]
When reviewing a created session, the date field appeared empty. I selected the date. 
I also elected to add a person, and used <return> to save.

Selected Home ( at top) to see session list, selected session, date not saved. Person saved.

How do I save a date?

Is it something I neglected to do at the start and a field that cannot later be amended?

I feel fairly certain I had saved a date when I made the recording; could a subsequent amendment or me adding a .jpg have unset the date ?

**Comment by Lingomat** [comment]
Please wire this up Sanga.
