### ISSUE TITLE
Language not in list

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#42]
Is it possible a language might not be in the list of recognised languages? I tried selecting Tuu or Taa language family but when used <return> would not save.

Only when I selected an option in the current list, would it enable the 'save' for the user.

**Comment by Lingomat** [comment]
Oh, I made the auto complete require a certain number of letters before it began, otherwise it was really slow.

**Comment by Lingomat** [comment]
No, the minimum length is 2 characters. Those don't seem to be ISO recognised languages. However you should be able to just type any name of a language you like, e.g. Womble, and hit return and it will enter (become a chip) and should save. It requires you hit return. Does this not work?

**Comment by Netesten** [comment]
Thanks for your email.

I was able to amend my Motto session.

I first tried adding a new session, but the app would not respond when I
pressed return, really odd.

maybe try again tomorrow.
