### ISSUE TITLE
Improve language selector directive

### ISSUE THREAD

**Issue by Lingomat** [aikuma/aikuma-ng#46]
If you enter a custom language of 'taa', this will be added as Taa as a 'chip' in the UI. When you navigate to some other view and then return, the language displayed will be the full string of a language that has 'taa' as the ISO code. This is undesirable.

Also consider that the auto complete should work by typing the iso language code. 

There probably needs to be a more robust approach to language name overrides also (we let the user type 中文 to select Chinese. However if they have typed Chinese, they still see 中文. So the best approach will be to implement a language override format, ideally in an external data file loaded along with the iso list, which specifies alternative names keyed by the localisation code.

**Comment by Netesten** [comment]
In case useful, I referred to https://en.wikipedia.org/wiki/N%C7%81ng_language

**Comment by Lingomat** [comment]
It turns out fixing this is more difficult because our data structure doesn't match what was originally intended. It needs to be fixed, but I'm sticking it on the backburner for now.

**Comment by Lingomat** [comment]
A short spell on the backburner :) This is the complete desired behavior for ng-language-selector.

The language selector autocomplete should pick up full language name text and it should pick up language iso codes. It should highlight search text in the options (just a flag).

Localised language name overrides. This feature is desirable so that users can use their language to search for languages that are most common for them. It will also be used to display the localised version of the language. We will store these language strings in the Angular Translate files with a special prefix. LANGISO_<code> 

(It will be necessary to get a list of these to build the autocomplete search string. It might be necessary to read the translation file directly rather than using $translate. It's still better than making our own files just for this).

Note: We need not care that current language selected chips will not change if we change the app language. The correct localisation can be done when the directive first initialises.

Custom languages. When the user types a language which does not exist and hits return, the language is saved on the user data in the same way as tags. Autocomplete will now recognise this custom language name in the future. While this is being done, we should store a list of all the languages that the user has ever selected, in the user data. This will be used for a language quick selector to be implemented later (and will be incorporated on language selector as a small button that pops up a list of languages the user has ever used, to be selected by mouse click instead of typing). When a custom language is displayed as a chip, we do not display the brackets and isocode because this is irrelevant.

Preference custom languages ahead of other results. This should be a matter of placing the custom languages at the top of the array used by autocomplete. 

Example: User has interface in Chinese. We have an override for Saisiyat (xsy) = 賽夏語. If the user types xsy and hits return rather than selecting an option, we should expand this fully to 賽夏語 (xsy). If by some remote chance they meant to actually enter a custom language called 'xsy' then it's apparent they need to call it something else. So they remove the chip, and type a fuller name.

**Comment by Lingomat** [comment]
Note: This is going to change the data structure and is going to break existing data for users.

This is problematic since Chrome Apps auto update. How do we address this? It seems like we might need a general data format upgrade scheme in case we wish to do this in future.

**Comment by Lingomat** [comment]
What is the status of this?

**Comment by lisaslyis** [comment]
For the localized language strings of one language, JSON file will be created, put in the same folder of ISO lang list and loaded in an app to construct the multi string options in language-selector autocomplete input: Chinese(cmn). 中文(cmn)， 漢語(cmn)， 國語(cmn)

**Comment by Lingomat** [comment]
Looks good!
