### ISSUE TITLE
Large inactive '+' icon

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#50]
Would ii be possible to replace the large inactive + with descriptive text: 
![image](https://cloud.githubusercontent.com/assets/18228507/14250205/be53fbe0-fac0-11e5-8855-abff43cc3d48.png)
It's size and scale do not seem to suit rest of UI.

**Comment by Lingomat** [comment]
Yes. This is tricky. The standard + button would end up directly on top of the + annotate button for a brand new session. I would like to avoid having text headlines in the session view. Other UI suggestions welcome. Different kind of + button icon is one choice, but it will still look strange directly on top of the + annotation button.

**Comment by Lingomat** [comment]
When looking at this I found a bug where the default location and description details were not being listed. I also changed the add card to look like the previous cards. 

Thanks for this report, it was helpful!
