### ISSUE TITLE
Save button disabled

### ISSUE THREAD

**Issue by hatton** [aikuma/aikuma-ng#51]
I'm using beta 0.905, Windows 10, and I can make a recording, but the Save button is always disabled, so I can't do anything else. What I am missing?

![image](https://cloud.githubusercontent.com/assets/8448/14285639/9607cbd2-fb09-11e5-82ba-627fbef8b2e1.png)

**Comment by Lingomat** [comment]
Ah,You haven't hit return in the language textbox, it's a chips-based UI so it only works out what to do when you select something from the autocomplete dropdown or hit return to enter a language that isn't in the ISO code list.  I've just pushed a new build which has validation messages.

**Comment by hatton** [comment]
Pressing enter fixed it.
