### ISSUE TITLE
Add Home to side bar

### ISSUE THREAD

**Issue by hatton** [aikuma/aikuma-ng#54]
For a long while I couldn't figure out how to see my old recordings; because the side bar appeared to be a list of all the places/activities, I was just... stumped to not find something there. I eventually found that the word "Home" is a clickable thing which took me to where I wanted to go.

I suggest adding it to the side bar. The word "Sessions" would have helped me find it faster than "home", but I understand "Home" has other benefits.

**Comment by Lingomat** [comment]
Implemented in 907. Excellent, thanks John :)

Sessions is a bit tricky cross-linguistically, home is universal.
