### ISSUE TITLE
Test speech recognition

### ISSUE THREAD

**Issue by Lingomat** [aikuma/aikuma-ng#58]
@Netesten please try out the speech recognition. On the annotation UI, press the microphone icon to the right of an annotation box and select a language (You could try British English), then mark or navigate to a region as normal and press the ` key (should be top left of your keyboard) and speak.

**Comment by Netesten** [comment]
[image: Inline images 1]
Am I in the correct window?

**Comment by Netesten** [comment]
![image](https://cloud.githubusercontent.com/assets/18228507/14354553/1b3112f0-fd21-11e5-8d1d-ee80dadcbf57.png)

**Comment by Netesten** [comment]
Just wondering if I am looking at the latest version of the app? I could also be in the wrong window possibly.

**Comment by Lingomat** [comment]
Looks like it hasn't updated yet. Need 908. You can see version bottom left of the app.

**Comment by Netesten** [comment]
ok, maybe tomrrow, might hit the sack. 12:50am
xxxxxxx

all the best with the hardcore coding XXXXXXX

**Comment by Netesten** [comment]
Friday 8pm, a day later, I still only have ver 0.904

might uninstall and reinstall

**Comment by Netesten** [comment]
aha!
now somehow have 0.909

excellent!

**Comment by Lingomat** [comment]
There is a way to force update. I might need to put it in instructions somewhere.

**Comment by Lingomat** [comment]
http://gadgets.ndtv.com/apps/features/how-to-manually-update-google-chrome-extensions-661907

**Comment by Lingomat** [comment]
Well in lieu of hearing anything about speech recognition, I'll close this. We can always open an issue if something comes up but it looks like it works pretty well.

**Comment by Netesten** [comment]
When I opened Aikuma on 11 Apr after last working on it maybe 9th Apirl, it
was ver 0.910 without me doing anything to go from 0.909.

I did the 'tick developer mode' and 'update extensions now', but it looks
the same

so i reckon it's ok

see what it does next time i log in


which is when ? when do you need the next bunch of testing done?
