### ISSUE TITLE
Delete comment in annotation area seems to fail

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#63]
I delete and confirm deletion of a comment in annotation area, but comment seems to remain.

**Comment by Lingomat** [comment]
This is on the the session view?  There's a list of annotations and you're clicking on the red cross to delete,  select confirm and nothing happens?

**Comment by Netesten** [comment]
ok, screenprinting process: 1
![image](https://cloud.githubusercontent.com/assets/18228507/14383372/07ff07fc-fdd8-11e5-88e0-2b45e9bb972b.png)

2. want delete first one
![image](https://cloud.githubusercontent.com/assets/18228507/14383390/28ee2042-fdd8-11e5-81be-e783c7570012.png)

3. press delete, but remains
![image](https://cloud.githubusercontent.com/assets/18228507/14383401/3f023d28-fdd8-11e5-82ec-3144f1ac4ec3.png)

**Comment by Lingomat** [comment]
Yarp, bug, thanks.

**Comment by Lingomat** [comment]
b1e55088bf9e5b7504fd88e6bd93507d2a0143e1 resolved

**Comment by Netesten** [comment]
Deleting an Annotation of the type Comment works for me. Thanks.
