### ISSUE TITLE
Select non-conflicting key for speech recognition

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#65]
Annotate view. Just used <ctrl> and right arrow key to get to the segment I want to leave a Comment about.
I start typing 
1. annoyingly punctuation is not allowed e.g. ' as in mother's 
2. suddenly I start getting loudly beeped at
3. the microphone icon starts blinking
4. my typed up text disappears ...
Perplexing. I will try again.

**Comment by Lingomat** [comment]
Okay so this seems related to me choosing ` as a key to start voice recognition. I'm baffled because we seldom use this in English, we use ' instead. Well, it seems that you use the ` key!

So clearly we need to change this, hmm. We're a bit short of obvious function keys for this. We're using control, tab and cursors. We can't use shift because it's used for typing. Alt has issues for Macs.

**Comment by Lingomat** [comment]
Hmm, I wonder if we could maybe get rid of tab for switching tracks and perhaps have the annotation keys (cursor up and down) shift between tracks as well. 

At this point I don't really understand how/if someone might use several tracks but  golly it would be nice to use tab to activate speech recognition.

**Comment by Netesten** [comment]
hm, I used ' not ` tho ...

**Comment by Netesten** [comment]
does the app on my pc think ' = ` ?  I am using spacesaver keyboard and it's keys are reversed, like @ is "

**Comment by Netesten** [comment]
Take 2: I was in the Home / Koejawels screen and clicked on the 'Annotate' . It goes into the Annotate screen. I click on the Annotate line, and it becomes live (with a cursor at start of line).
I use < Ctrl> and right arrow to get to the second segment to make sure that's the one that needs the note. (does the green highlighting region thing)
Yes, It is when I use the apostrophe ' (for mother's) that the sharp beep happens, microphone blinks and beeps again (two). Somehow my ' is triggering your `  ?
When I click ' nothing happens onscreen.
Tried to grab a screenshot here 
![image](https://cloud.githubusercontent.com/assets/18228507/14384735/f18de918-fddf-11e5-8d1e-b19d34b77685.png)

**Comment by Netesten** [comment]
what about <insert> or <Pg Up> or <Pg Down> or <Home> or <End> keys ? <Insert> sounds kind of good? It's right next to the right-arrow ....

**Comment by Lingomat** [comment]
You know you can't type them right? :) The normal ' is usually down by the enter key.

**Comment by Lingomat** [comment]
Resolved by 59985918ee12d034832943fcc876f47e1c598ee3 - changed to backslash.

**Comment by Netesten** [comment]
I can type a possessive/apostrophe ' in the Comments now - thanks!

**Comment by Lingomat** [comment]
Cool. You're typing the regular apostrophe here so I'm not sure how this is happening. I need to take a look at your computer and keyboard layout.

**Comment by Netesten** [comment]
hello Miaoli Mat xxx

Had another go

Yes, using ' next to the Enter key - picture further below:

Here's where I was:
[image: Inline images 1]

Specifically, for purposes of tonight, typing the last line:
[image: Inline images 2]

**Comment by stevenbird** [comment]
I'm happy to drop the use of tab for switching between annotations.
