### ISSUE TITLE
Investigate Chrome on iOS for Aikuma

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma-ng#68]

**Comment by Lingomat** [comment]
I think this needs to be done via an Apache Cordova build. It wont be Chrome as such. Similar to Android.

**Comment by Lingomat** [comment]
You know what, I reckon a Cordova build ought to be a fork. I also think it would need it's own development lead.

**Comment by Lingomat** [comment]
It should be possible to build a web app that will work on the iOS browser. If that fails then the solution is a cordova build for iOS to make an installable app.
