### ISSUE TITLE
Find on screen 

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#76]
This may not be an issue.

<ctrl> F : is not active on e.g. 'Changes' page

Helps find quicker e.g. 'toast'

**Comment by Lingomat** [comment]
Confused. You can't type control-F?

**Comment by Netesten** [comment]
I can type <ctrl> F: but it does not produce a search box where I can state my criteria

**Comment by Lingomat** [comment]
Ah of course, this doesn't work at all in a Chrome packaged app. Hmm. There is a solution, we could use a <webview> to show the changes page. This would also need to be added to the manifest. Hmm, need to think about this.

**Comment by Lingomat** [comment]
This is a laborious solution for a real edge case need. I'm happy to look at search for things like transcripts/annotations, but for I don't think we'll do it for this.
