### ISSUE TITLE
Respeak mode: indicate Microphone active?

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#78]
Not an issue, just a UI tweak?

when respeaking, I use shift left to hear the segment, then I click microphone icon to respeak it - I think would help if microphone icon would show it's working by becoming dark green, like the play button

**Comment by Lingomat** [comment]
Err yes, it does actually but because your mouse is hovering over it, you don't see the colour change. If you use right-shift instead, you see it change.

**Comment by Lingomat** [comment]
Sorted. No green/red now, they both go the primary colour (that aqua colour) but this happens even if you use the mouse or have it hovered over the buttons.

**Comment by Netesten** [comment]
[image: Inline images 1]

just a postscript!

Yes, when my eyes look right, they see your text and when I hold leftshift
, the play button does show active colour: sorry for missing.

However, if my eyes look left, they see a play button that looks receptive
to a keypress (not greyed out) and when I click it not too much happens.
Was just thinking, if that play button was greyed at the start, the eye has
to find another clue to get going on the app. when the person clicks left
shift, the play button could get active colour?
