### ISSUE TITLE
Help icons for Annotation area?

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#79]
Again, not an issue, just to help the user: how about a '?' with a scrap of help: like : when I add an annotation it asks me for a language: am I to attach the language I am recording in; what do I record if I am commenting in English on my Afrikaans respeaking ; or if I was commenting in German, on an Italian respeaking of French recording? (theoretically speaking). If we record all languages involved, is there a need to tag what's happening/function of each, because they play different roles?

**Comment by Lingomat** [comment]
Oooo... I keep forgetting about this, yes absolutely. So add ? to language selector directive and insert some text explaining what the language should be. It should be the language of the recording or annotation. 

An italian respeaking of a french recording is a translation :) The language selector is supposed to indicate the language of that particular record. So if you're translating to Italian, you'd put Italian for that. The source recording would be marked French when you imported or recorded.

**Comment by Lingomat** [comment]
So... for the sake of clarity, perhaps all of the directives should have a ? on the right hand side which explains what they are. So you'd see a row of three ? vertically for the language, speaker and tag directives on the session view. I wonder. If the text is simple, perhaps we could just tool-tip the ? instead of a pop up dialog? For example:

Tags: Apply your own labels to describe this recording. Example: #grandparents, #lowquality, #notfinished etc.

**Comment by Netesten** [comment]
Thinking about identifying the language and the function of that language.

Going forward, looking to the future: assuming a great Aikuma success, and
many databases full of recordings, translations and respeakings: would a
researcher want to run a search to find and obtain all recordings in a
specific language?

Is there a definite need for specificity?

Sometimes valuable information is lost because it is not captured at the
most pertinent point: by the person who knows best - the maker of the
recording, esp with a disappearing language / a person who may not be
around very long.

It may seem that this is a small piece of information but I believe if it
is of vital importance, it should not be programmed out.
I have encountered before where the loss of information deemed not
important crippled software. Hence the impassioned plea - please rethink in
case the position of the language is very important to a future researcher.

**Comment by Netesten** [comment]
Please ignore if irrelevant :)

**Comment by Lingomat** [comment]
I don't quite understand. I'm not suggesting removing anything? I'm just interested in providing clarity over what the language selector is for. It's precisely so that the data field is useful in searches and what have you.

**Comment by Netesten** [comment]
Sorry about the crossed wires!

Re: "all of the directives should have a ? on the right hand side which
explains what they are. So you'd see a row of three ? vertically for the
language, speaker and tag directives on the session view. I wonder. If the
text is simple, perhaps we could just tool-tip the ? instead of a pop up
dialog? For example:

Tags: Apply your own labels to describe this recording. Example:
#grandparents, #lowquality, #notfinished etc."
So, in this screen - are we talking vertical '?' in line with the
Translation's Annotation's 'X'  or thereabouts ....
[image: Inline images 4]

.. or when the user clicks on Add new annotation ->
adding  the '?' next to where it has 'Languages' in grey?
[image: Inline images 3]

My concern was that somehow that the recording language and translation
languages would get mixed up, or if the user didn't know what to be
assigning
e.g. for a translation putting in two languages, where maybe it needs to
just be the language that the translation is in.
