### ISSUE TITLE
Can't delete a recording

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#80]
I made a test recording. How do I delete it? It appears in Home but no 'X' icon

**Comment by Lingomat** [comment]
I guess you mean delete an entire session. No way to do that actually, never occurred to me. 

We should add this but it must trigger a dialog to confirm, with a default action of cancel. If it wasn't for the pain of localisation, I'd even favour having the user type yes or delete in a box to confirm. Actually we would do that no? Have the pop up controller fetch the localised string for 'delete', say', and then checking that a form input === this string. 

Sanga, can you implement a delete session function? Obviously it needs to delete all files associated with it. I'll handle the UI.

**Comment by Netesten** [comment]
that would be great. I managed to create a recording of nothing and it
clutters my view of actual recordings.

Say, if a person was prolific, would the font re-size smaller to see more
on the screen?

Also would the screen how file type attributes like date to sort by?
Or are search filters a possibility, or is that more a thing that happens
when the recordings are uploaded into a database ?

**Comment by Lingomat** [comment]
Right now what we do is sort by the time that the session was last modified. You know, I haven't even tested if the homepage scrolls if there's a lot of sessions.

You're right, we will do something more sophisticated when the online database is in play but... it doesn't seem unreasonable to offer the user the chance to sort by the fields they wish...

Also, we need a session summary line for each session, that gives a better idea at a glance. Not entirely sure what that might be... they could do an animated cycle through annotation text...

**Comment by Netesten** [comment]
Just wondering, about fitting more on screen, is it desirable for the
target population to be able see a smaller font, with <ctrl,>// - or
whatever the key combo is to display smaller font

**Comment by Netesten** [comment]
Just wondering, about fitting more on screen, is it desirable for the
target population to be able see a smaller font, with <ctrl,>// - or
whatever the key combo is to display smaller font
On 24/04/2016 7:27 am, "Jeannine Bettinson" <neen.bettinson@gmail.com>
wrote:

What about using the description, and add a tooltip or '?' To descrlption,
explain it needs to be a concise identifier, or sunbathing like that

**Comment by Netesten** [comment]
Sent too soon, control and minus key combo to zoom smaller, is what i
wanted to say

**Comment by Lingomat** [comment]
Hmm, I've set somewhat chunky fonts because Chinese ends up being too small otherwise. In a Chrome App you can't change the size yourself but it might be possible to offer that in settings, hmm.

**Comment by stevenbird** [comment]
I recommend a two stage process, in which deleted sessions or annotations etc are moved to the trash, and where it's a separate decision to empty the trash. The first step can be implemented as a boolean, which does nothing more than hide the item from bring listed (ie no need to move files)

**Comment by Lingomat** [comment]
Great, so we make a trash entry on the nav bar I guess. and we show a list of sessions there but just with the trash flag. This page can offer the ability to clear trash.

**Comment by Lingomat** [comment]
I think we can tackle #48 by having rename on the home page rather than the session view.

**Comment by Lingomat** [comment]
137bf3988816bfdbb0a6e94a162a9e59922a43b4 improves session display. While I'd like to perhaps show some annotation snippets too, this turns out to be very slow with our back end.

**Comment by Netesten** [comment]
okay, just checking - does this mean I can delete a recording ?
Can't see how to delete as yet.
Is right-click delete a possibility?
I have version 0.928.

**Comment by Netesten** [comment]
Great - just successfully used the Bin/Trash icon to delete four recordings, found them in the DELETED ITEMS menu on the left, restored one, deleted it again from Home. Then permanently deleted all four. Using v.0930
