### ISSUE TITLE
Should identical recording names/titles prompt a pop-up or auto rename 1,2, 3?

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#81]
![image](https://cloud.githubusercontent.com/assets/18228507/14759913/0215aff8-0977-11e6-9f94-6abf7ff7d789.png)

I made two 'Testing' recordings. Should the app have the normal PC behaviour 'this filename exists, do you want to overwrite or rename? with save as box popping up if requested?

**Comment by Lingomat** [comment]
Yes, excellent. It should just append (2) after. Sanga, if session name collision (non case sensitive) then append (numeral) and loop until it's unique.

**Comment by Lingomat** [comment]
Resolved with 5fcf411debd94bc5a773b40a2aa2a1eb53d2cb0c

**Comment by Netesten** [comment]
Now I make 'testing' and 'testing' and the second one saves as 'testing(1)' - where do I get to rename the files ?
