### ISSUE TITLE
About Aikuma-NG not open with ver. 0.930

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#87]
Click on About Aikuma-NG, nothing happens

**Comment by Lingomat** [comment]
Cannot reproduce, don't see why this would have changed.

**Comment by Netesten** [comment]
Figured this out.

I was hovering the mouse over the top of the icon, and the tooltip, 'About
Aikuma-NG' popped up and I was (ahem) trying to click that. Fail.
Now, when I click lower down, launches expected window.

Tiredness+user error, methinks!

**Comment by Lingomat** [comment]
Cool. I moved the about down to the little version string bottom left anyway.
