### ISSUE TITLE
Incomplete translation - user guidance requested

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#89]
I make a recording.
I translate. There's a bunch of silence at the end. 
I hold the left shift to hear up until the words stop. I right shift and translate. There's the silence I ignore.
I save.
In session view I click on translation. It offers me new or to continue. Continue puts me back in the work view and I have no idea what to do. 
Can you make this clearer to the user please?

**Comment by Lingomat** [comment]
Hmm. Not sure I follow. You can continue respeaking or translating because you might be working on a long file and you're too tired to do it all in one sitting. Or you might want to make a new one, how else could we describe?

**Comment by Netesten** [comment]
But it's only recording silence that's left to translate. Don't know how
mark it complete

**Comment by Lingomat** [comment]
It doesn't have to be made complete. You can work with it in the annotator, or make a new one if you wish.

**Comment by Lingomat** [comment]
Would appreciate a suggestion how to make this clearer in the UI. The purpose of the tick was to give you the impression that you were done with the respeak/translate.

**Comment by Netesten** [comment]
This is what needed clarifying for me:
I translate a recording. I get to what seems to be the end.
I click the tick, thinking 'that's done'.

In the session view, if I click on the horizontal Translation (1) button,
it offers me to Record new or Continue with translating 1.
I find it frustrating because I don't know what to do - I finished
translating, why does it think I want to carry on?

You explained that the user here may be wanting to refine that particular
translation.
My musunderstanding.

Maybe it could be made clearer :
click this translate if you want to continue refining this translation.
click that translation if you want to hear the recording followed by the
translation.

Maybe only clarify if others find this confusing too.

**Comment by Lingomat** [comment]
Okay, thanks for the feedback on this. I'll keep an eye on it when doing user testing here.
