### ISSUE TITLE
Persistent button

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#90]
In Translation work view
![image](https://cloud.githubusercontent.com/assets/18228507/14883766/6983c5fc-0d83-11e6-90a6-34cd17bf7a44.png)

I decide to go to session view:
![image](https://cloud.githubusercontent.com/assets/18228507/14883784/8d6413be-0d83-11e6-8421-4a5f107b84b7.png)

The Cancel button persists

**Comment by Lingomat** [comment]
Sometimes these things happen when we do a lot of conditional templating with md-tooltip. The solution is usually just to make a single <div ng-if=""> with the correct versions of the button rather than try and switch in and out tooltips in the middle of buttons.

**Comment by Netesten** [comment]
This looks fixed, not happening when I go into the workscreens for
respeaking and translating

Thanks
