### ISSUE TITLE
Translation playback skips every 2nd region

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#91]
I make a recording.
I make a translation.
I go to session view.
I click Translation. I expect, as before, to hear first region of recording followed by first region's translation, second region and so on.
What happens is every second region is skipped ie 2nd, 4th, etc

**Comment by Lingomat** [comment]
Is it playing okay in the annotation UI?

**Comment by Lingomat** [comment]
Replicated. I've broken something..

**Comment by Netesten** [comment]
My playback does not skip translation regions any more.
However, it's clipping the segments and while the first region plays back
as desired - first clearly the recording then it's translation, after that
it gets messy, segments run into each other, get chopped off, mixed. Tried
it three times - made different recordings.
