### ISSUE TITLE
Visual text collisions

### ISSUE THREAD

**Issue by nyborrobyn** [aikuma/aikuma-ng#95]
If a typed line is long, it collides with the following line visually.
![screen shot 2016-04-28 at 15 46 50](https://cloud.githubusercontent.com/assets/5350255/14924907/8715a39e-0df9-11e6-9268-ea00bcdfc2f6.png)

Not sure the best fix. Perhaps each line that's too long being shown to the permitted length followed by trailing '...' to indicate that it keeps going.

**Comment by Lingomat** [comment]
Thanks. I think given it's a transcript we would just expand that box rather than having fixed sizes. That's how it was supposed to work.
