### ISSUE TITLE
Arrow buttons challenging for text editing (in annotation screens)

### ISSUE THREAD

**Issue by nyborrobyn** [aikuma/aikuma-ng#96]
This might just be something I have to learn, so feel free to close issue, but sharing for your info:

When trying to edit a typed transcription, I use my arrow keys a lot out of habit to move quickly across words. It's taking me a little while to learn to not use those keys for moving within what I've written. I can’t use keystrokes I’m used to like ctrl+—> or ctrl+<— or it skips to the next region/translation section. 

So I know I have to learn that. But when doing translation annotation, if I use <— on accident thinking I can edit my sentence, I jump to previous section AND lose the translation text I've just typed. Would it be possible to have the text I've written remain if I try to get it back with —>?

**Comment by Lingomat** [comment]
Ah I see. I hadn't thought of that.

So it strikes me that one solution would be to put the arrow keys on a qualifier for annotation navigate instead. Like shift left and shift right. Then arrows would work as you expect inside an annotation box.

How's that? @stevenbird what do you think?

**Comment by nyborrobyn** [comment]
Yes, seems like a good idea, if I'm understanding right.

**Comment by Lingomat** [comment]
Implemented. I think I left cursor up and down as they were though, so they don't care if you hold shift or not.
