### ISSUE TITLE
Translation playback incorrect

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#98]
In the session view, when I select Translation (the vertical one, not the horizontal option higher up) it seems to mess up the second and maybe the fifth region playback of the translation (six regions in total).

The first region plays back as expected - first clearly the recording then the translation. 

Not so the second. The translation is incorrect - it played the 4th and 5th regions' translations.

**Comment by Lingomat** [comment]
Hrm, that's a worry. I need to duplicate this to address it.

**Comment by Netesten** [comment]
I made another recording and sent it to your Messenger. The recording is in English of 1 to 10, translated into Afrikaans, and it is super-skippy.
It used to be fine, round about ver 0.930? or one before. Then - was it the time stretching code ?
it was being messy playback. 
I have not really used the timestretching since, actually.
Anyway, hope the clip helps.

**Comment by Lingomat** [comment]
Confirmed, the ordering of playing back of secondary audio is incorrect.

**Comment by Lingomat** [comment]
Turns out this is MediaElement again. The data was fine. MediaElement audio seeking is essentially broken as far as I can tell.
