### ISSUE TITLE
Translation playback when more than one

### ISSUE THREAD

**Issue by Netesten** [aikuma/aikuma-ng#99]
Question: I make two translations. When I select translation playback, I am not given an option as to which to play. Should there be a list to pick from if there is more than one?

**Comment by Lingomat** [comment]
They should both show up though... so it's a matter of which one you click on.

**Comment by Lingomat** [comment]
You might be a bit confused since previously they were displayed in the drop down menu. But now they appear in the consolidated annotation list view. So you will have two translations appearing right?

**Comment by Lingomat** [comment]
What should happen is that the two translations should be numbered 1 and 2, and this isn't happening at the moment. So I'll alter this issue to address that UI change.
